fragment PostParts on Post {
  title
  heroImg
  excerpt
  author {
    ... on Document {
      id
    }
  }
  date
  section
  tags
  _body
  meta {
    __typename
    description
    og {
      __typename
      type
      image
      namespace {
        __typename
        value
        uri
      }
      customMeta {
        __typename
        property
        content
      }
    }
  }
}

fragment GlobalParts on Global {
  head {
    __typename
    title
    meta {
      __typename
      description
    }
  }
  header {
    __typename
    icon {
      __typename
      color
      style
      name
    }
    brand
    color
    nav {
      __typename
      href
      label
    }
  }
  footer {
    __typename
    color
    social {
      __typename
      facebook
      twitter
      linkedin
      github
    }
    viewRawDataButton
  }
  theme {
    __typename
    color
    font
    icon
    darkMode
  }
}

fragment AuthorParts on Author {
  name
  avatar
}

fragment PageParts on Page {
  title
  blocks {
    __typename
    ... on PageBlocksImageTextSection {
      sectionLabel
      id
      headline
      text
      image {
        __typename
        src
        alt
      }
      color
    }
    ... on PageBlocksHero {
      sectionLabel
      id
      tagline
      headline
      text
      actions {
        __typename
        label
        type
        icon
        link
      }
      image {
        __typename
        src
        alt
      }
      color
    }
    ... on PageBlocksFeatures {
      sectionLabel
      id
      items {
        __typename
        icon {
          __typename
          color
          style
          name
        }
        image {
          __typename
          src
          alt
        }
        title
        text
      }
      color
    }
    ... on PageBlocksContent {
      sectionLabel
      id
      body
      color
    }
    ... on PageBlocksTwoColumnsContent {
      sectionLabel
      id
      headline
      firstColumn {
        __typename
        headline
        text
        image {
          __typename
          src
          alt
          hyperlink
        }
      }
      secondColumn {
        __typename
        headline
        text
        image {
          __typename
          src
          alt
          hyperlink
        }
      }
      color
    }
    ... on PageBlocksTestimonial {
      sectionLabel
      id
      quote
      author
      color
    }
  }
  meta {
    __typename
    description
    og {
      __typename
      type
      image
      namespace {
        __typename
        value
        uri
      }
      customMeta {
        __typename
        property
        content
      }
    }
  }
}
